// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Thuto.Data;

#nullable disable

namespace Thuto.Migrations
{
    [DbContext(typeof(ThutoDataContext))]
    [Migration("20261003210344_AddPasswordResetTokens")]
    partial class AddPasswordResetTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Thuto.Models.Career", b =>
                {
                    b.Property<int>("CareerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CareerID"));

                    b.Property<string>("CareerDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CareerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CareerID");

                    b.ToTable("Career", (string)null);
                });

            modelBuilder.Entity("Thuto.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseID"));

                    b.Property<string>("CareerOpportunities")
                        .HasColumnType("text");

                    b.Property<string>("CourseCode")
                        .HasColumnType("text");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DurationYears")
                        .HasColumnType("integer");

                    b.Property<string>("EntryRequirements")
                        .HasColumnType("text");

                    b.Property<int?>("MinimumAPS")
                        .HasColumnType("integer");

                    b.Property<string>("QualificationType")
                        .HasColumnType("text");

                    b.Property<string>("StudyLevel")
                        .HasColumnType("text");

                    b.HasKey("CourseID");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("Thuto.Models.CourseCareer", b =>
                {
                    b.Property<int>("CourseID")
                        .HasColumnType("integer");

                    b.Property<int>("CareerID")
                        .HasColumnType("integer");

                    b.HasKey("CourseID", "CareerID");

                    b.HasIndex("CareerID");

                    b.ToTable("CourseCareer", (string)null);
                });

            modelBuilder.Entity("Thuto.Models.CourseOffered", b =>
                {
                    b.Property<int>("OfferingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OfferingID"));

                    b.Property<int?>("APSRequirement")
                        .HasColumnType("integer");

                    b.Property<string>("AdmissionRequirements")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationInformation")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationURL")
                        .HasColumnType("text");

                    b.Property<int>("CourseID")
                        .HasColumnType("integer");

                    b.Property<int>("FacultyID")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectRequirements")
                        .HasColumnType("text");

                    b.Property<int>("UniversityID")
                        .HasColumnType("integer");

                    b.HasKey("OfferingID");

                    b.HasIndex("CourseID");

                    b.HasIndex("FacultyID");

                    b.HasIndex("UniversityID");

                    b.ToTable("CourseOffered", (string)null);
                });

            modelBuilder.Entity("Thuto.Models.Document", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.HasKey("DocumentID");

                    b.ToTable("Document", (string)null);
                });

            modelBuilder.Entity("Thuto.Models.Faculty", b =>
                {
                    b.Property<int>("FacultyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FacultyID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UniversityID")
                        .HasColumnType("integer");

                    b.HasKey("FacultyID");

                    b.HasIndex("UniversityID");

                    b.ToTable("Faculty", (string)null);
                });

            modelBuilder.Entity("Thuto.Models.Funding", b =>
                {
                    b.Property<int>("FundingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FundingID"));

                    b.Property<string>("ApplicationURL")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Eligibility")
                        .HasColumnType("text");

                    b.Property<string>("FundingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FundingType")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.HasKey("FundingID");

                    b.ToTable("Funding", (string)null);
                });

            modelBuilder.Entity("Thuto.Models.ImportantDate", b =>
                {
                    b.Property<int>("DateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DateID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DateType")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("URL")
                        .HasColumnType("text");

                    b.Property<int>("UniversityID")
                        .HasColumnType("integer");

                    b.HasKey("DateID");

                    b.HasIndex("UniversityID");

                    b.ToTable("ImportantDate", (string)null);
                });

            modelBuilder.Entity("Thuto.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Thuto.Models.PinnedCourse", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("CourseID")
                        .HasColumnType("integer");

                    b.HasKey("UserID", "CourseID");

                    b.HasIndex("CourseID");

                    b.ToTable("PinnedCourse", (string)null);
                });

            modelBuilder.Entity("Thuto.Models.PinnedUniversity", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("UniversityID")
                        .HasColumnType("integer");

                    b.HasKey("UserID", "UniversityID");

                    b.HasIndex("UniversityID");

                    b.ToTable("PinnedUniversity", (string)null);
                });

            modelBuilder.Entity("Thuto.Models.University", b =>
                {
                    b.Property<int>("UniversityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UniversityID"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("InstitutionType")
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .HasColumnType("text");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniversityType")
                        .HasColumnType("text");

                    b.Property<string>("WebsiteURL")
                        .HasColumnType("text");

                    b.HasKey("UniversityID");

                    b.ToTable("University", (string)null);
                });

            modelBuilder.Entity("Thuto.Models.UniversityFunding", b =>
                {
                    b.Property<int>("UniversityID")
                        .HasColumnType("integer");

                    b.Property<int>("FundingID")
                        .HasColumnType("integer");

                    b.HasKey("UniversityID", "FundingID");

                    b.HasIndex("FundingID");

                    b.ToTable("UniversityFunding", (string)null);
                });

            modelBuilder.Entity("Thuto.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Thuto.Models.UserDocument", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int>("DocumentID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.HasKey("UserID", "DocumentID");

                    b.HasIndex("DocumentID");

                    b.ToTable("UserDocument", (string)null);
                });

            modelBuilder.Entity("Thuto.Models.CourseCareer", b =>
                {
                    b.HasOne("Thuto.Models.Career", "Career")
                        .WithMany("CourseCareers")
                        .HasForeignKey("CareerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thuto.Models.Course", "Course")
                        .WithMany("CourseCareers")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Career");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Thuto.Models.CourseOffered", b =>
                {
                    b.HasOne("Thuto.Models.Course", "Course")
                        .WithMany("CourseOfferings")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thuto.Models.Faculty", "Faculty")
                        .WithMany("CourseOfferings")
                        .HasForeignKey("FacultyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thuto.Models.University", "University")
                        .WithMany("CourseOfferings")
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Faculty");

                    b.Navigation("University");
                });

            modelBuilder.Entity("Thuto.Models.Faculty", b =>
                {
                    b.HasOne("Thuto.Models.University", "University")
                        .WithMany("Faculties")
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("Thuto.Models.ImportantDate", b =>
                {
                    b.HasOne("Thuto.Models.University", "University")
                        .WithMany("ImportantDates")
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("Thuto.Models.PinnedCourse", b =>
                {
                    b.HasOne("Thuto.Models.Course", "Course")
                        .WithMany("PinnedCourses")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thuto.Models.User", "User")
                        .WithMany("PinnedCourses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thuto.Models.PinnedUniversity", b =>
                {
                    b.HasOne("Thuto.Models.University", "University")
                        .WithMany("PinnedUniversities")
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thuto.Models.User", "User")
                        .WithMany("PinnedUniversities")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thuto.Models.UniversityFunding", b =>
                {
                    b.HasOne("Thuto.Models.Funding", "Funding")
                        .WithMany("UniversityFundings")
                        .HasForeignKey("FundingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thuto.Models.University", "University")
                        .WithMany("UniversityFundings")
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funding");

                    b.Navigation("University");
                });

            modelBuilder.Entity("Thuto.Models.UserDocument", b =>
                {
                    b.HasOne("Thuto.Models.Document", "Document")
                        .WithMany("UserDocuments")
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thuto.Models.User", "User")
                        .WithMany("UserDocuments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thuto.Models.Career", b =>
                {
                    b.Navigation("CourseCareers");
                });

            modelBuilder.Entity("Thuto.Models.Course", b =>
                {
                    b.Navigation("CourseCareers");

                    b.Navigation("CourseOfferings");

                    b.Navigation("PinnedCourses");
                });

            modelBuilder.Entity("Thuto.Models.Document", b =>
                {
                    b.Navigation("UserDocuments");
                });

            modelBuilder.Entity("Thuto.Models.Faculty", b =>
                {
                    b.Navigation("CourseOfferings");
                });

            modelBuilder.Entity("Thuto.Models.Funding", b =>
                {
                    b.Navigation("UniversityFundings");
                });

            modelBuilder.Entity("Thuto.Models.University", b =>
                {
                    b.Navigation("CourseOfferings");

                    b.Navigation("Faculties");

                    b.Navigation("ImportantDates");

                    b.Navigation("PinnedUniversities");

                    b.Navigation("UniversityFundings");
                });

            modelBuilder.Entity("Thuto.Models.User", b =>
                {
                    b.Navigation("PinnedCourses");

                    b.Navigation("PinnedUniversities");

                    b.Navigation("UserDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
